"""
Script that regnerates the plugins table in ``README.md``.

Usage::

    python scripts/make_table.py

This script assumes that you have installed this repository in your FiftyOne
plugins directory::

    cd /path/to/fiftyone-plugins
    ln -s "$(pwd)" "$(fiftyone config plugins_dir)/fiftyone-plugins"

| Copyright 2017-2023, Voxel51, Inc.
| `voxel51.com <https://voxel51.com/>`_
|
"""
import argparse
import os

from jinja2 import Environment, BaseLoader

import fiftyone as fo
import fiftyone.operators as foo
import fiftyone.plugins as fop

# The images for the templates below are located at
# https://github.com/voxel51/fiftyone-examples/issues/11

TOC_TEMPLATE = """
<!-- Autogenerated by `scripts/make_table.py` -->
<table>
    <tr>
        <th colspan="6">Available Plugins</th>
    </tr>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Version</th>
        <th colspan="3" >Links</th>
    </tr>
{% for plugin in plugin_list %}
    <tr>
        <td><b><a href="{{ plugin.href }}">{{ plugin.name }}</a></b></td>
        <td>{{ plugin.desc }}</td>
        <td><code>{{plugin.version}}</code></td>
        <td><a href="{{ plugin.about_href }}">About</a></td>
        <td><a href="{{ plugin.install_href }}">Install</a></td>
        <td>
        {% if plugin.has_operators %}
            <a href="{{ plugin.operators_href }}">Operators</a>
        {% endif %}
        </td>
    </tr>
{% endfor %}
</table>
"""


def _make_table():
    plugin_info = {
        p.name: {"plugin": p, "operators": []}
        for p in fop.list_plugins()
        if p.name.startswith("@voxel51")
    }

    for operator in foo.list_operators():
        idx = plugin_info.get(operator.plugin_name, None)
        if idx is not None:
            idx["operators"].append(
                {
                    "name": operator.name,
                    "label": operator.config.label,
                    "description": operator.config.description,
                }
            )

    plugin_list = []
    for name in plugin_info.keys():
        plugin = plugin_info[name]["plugin"]
        operators = plugin_info[name]["operators"]

        has_js = plugin.has_js
        has_py = plugin.has_py
        if has_js and has_py:
            types = "Python and JS"
        elif has_js:
            types = "JS"
        elif has_py:
            types = "Python"

        # url was added in fiftyone==0.21.1
        url = getattr(
            plugin, "url", "https://github.com/voxel51/fiftyone-plugins"
        )

        plugin_list.append(
            {
                "name": plugin.name,
                "desc": plugin.description,
                "href": url,
                "about_href": url,
                "install_href": f"{url}#installation",
                "operators_href": f"{url}#operators",
                "types": types,
                "has_operators": len(operators) > 0,
                "version": plugin.version,
                "license": plugin.license,
                "operators": operators,
            }
        )

    environment = Environment(
        loader=BaseLoader,
        trim_blocks=True,
        lstrip_blocks=True,
    )

    template = environment.from_string(TOC_TEMPLATE)

    return template.render(plugin_list=plugin_list)


def main(write=False):
    if write:
        raise NotImplementedError("The --write option is not yet implemented")

    table = _make_table()
    print(table)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-w",
        "--write",
        action="store_true",
        help="write the updated table to README.md",
    )
    args = parser.parse_args()

    main(write=args.write)
